name: VCPKG Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron:  '0 6 * * *'

jobs:
  build_linux:
    strategy:
      fail-fast: false
      matrix:
        image:
          - { name: 'ubuntu', tag: '18.04' }
          - { name: 'ubuntu', tag: '20.04' }
        llvm: [
          '9',
          '10',
          '11'
          ]

    runs-on: ubuntu-20.04
    container:
      image: docker.pkg.github.com/trailofbits/cxx-common/vcpkg-builder-${{ matrix.image.name }}:${{ matrix.image.tag }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Install utility tools
        shell: bash
        run: |
          apt-get update
          apt-get install -y pixz xz-utils

      - name: Build with build script
        shell: bash
        run: ./scripts/build.sh --llvm-version ${{ matrix.llvm }}

  build_mac:
    strategy:
      fail-fast: false
      matrix:
        os: [
          'macos-10.15',
          'macos-11.0'
          ]
        llvm: [
          '9',
          '10',
          '11'
          ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Build with build script
        shell: bash
        run: ./scripts/build.sh --llvm-version ${{ matrix.llvm }}
